# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/penpal

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            cd api
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            flask db upgrade
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            python -m pytest -v --cov=app