version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/penpal

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            cd api
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            FLASK_ENV=development flask db upgrade
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            python -m pytest -v --cov=app

workflows:
  main:
    jobs:
      - build-and-test
