"""empty message

Revision ID: 44221a826882
Revises: 9f047c4175a0
Create Date: 2020-08-23 15:21:03.083782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44221a826882"
down_revision = "9f047c4175a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=64), nullable=True),
        sa.Column("looking_for", sa.String(length=500), nullable=True),
        sa.Column("connection_type", sa.String(length=64), nullable=True),
        sa.Column("communication_type", sa.String(length=64), nullable=True),
        sa.Column("interest_type", sa.String(length=64), nullable=True),
        sa.Column("language_preference", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preference_language_mapping",
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("preference_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"],),
        sa.ForeignKeyConstraint(["preference_id"], ["preferences.id"],),
        sa.PrimaryKeyConstraint("language_id", "preference_id"),
    )
    op.add_column("interests", sa.Column("class", sa.String(length=64), nullable=True))
    op.add_column("interests", sa.Column("type", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interests", "type")
    op.drop_column("interests", "class")
    op.drop_table("preference_language_mapping")
    op.drop_table("preferences")
    # ### end Alembic commands ###
