"""empty message

Revision ID: 6c4a47715083
Revises: a44586581694
Create Date: 2020-08-13 19:45:47.730722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c4a47715083"
down_revision = "a44586581694"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birthdate", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "birthdate")
    # ### end Alembic commands ###
