"""empty message

Revision ID: 91ef3a6c3455
Revises: 44221a826882
Create Date: 2020-08-30 14:09:57.666186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91ef3a6c3455"
down_revision = "44221a826882"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("gender", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
