"""empty message

Revision ID: 9f047c4175a0
Revises: 
Create Date: 2020-08-17 21:53:54.393021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f047c4175a0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_countries_name"), "countries", ["name"], unique=True)
    op.create_table(
        "interests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity", sa.String(length=64), nullable=True),
        sa.Column("img", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interests_activity"), "interests", ["activity"], unique=True
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "penpals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("birthdate", sa.Date(), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("onboarded", sa.Boolean(), nullable=True),
        sa.Column("about_me", sa.String(length=500), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["country_id"], ["countries.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "letters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=1256), nullable=True),
        sa.Column("sent_date", sa.Integer(), nullable=True),
        sa.Column("edited_date", sa.Integer(), nullable=True),
        sa.Column("penpal_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["penpal_id"], ["penpals.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_interest_mapping",
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["interest_id"], ["interests.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("interest_id", "user_id"),
    )
    op.create_table(
        "user_language_mapping",
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("language_id", "user_id"),
    )
    op.create_table(
        "user_penpal_mapping",
        sa.Column("penpal_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["penpal_id"], ["penpals.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("penpal_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_penpal_mapping")
    op.drop_table("user_language_mapping")
    op.drop_table("user_interest_mapping")
    op.drop_table("letters")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("penpals")
    op.drop_table("languages")
    op.drop_index(op.f("ix_interests_activity"), table_name="interests")
    op.drop_table("interests")
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
